version: '3'
networks:
  default:
    name: host
services:
  nextjs:
    build:
      context: .
    # networks:
    # - nextts-rest-redux-panel-nginx_host
  nginx:
    build:
      context: ./nginx
    # networks:
    # - nextts-rest-redux-panel-nginx_host
    ports:
      - 80:80
# networks:
#   host:
#     driver: host
# networks:
#   default:
#     external:
#       name: host
