version: '3'
services:
  nextjs:
    build: ./
    networks:
      - host
  nginx:
    build: ./nginx
    networks:
      - host
    ports:
      - 80:80
networks:
  host:
    driver: host
# networks:
#   default:
#     external:
#       name: host
