version: '3.4'
services:
  nextjs:
    restart: always
    build:
      context: .
      network: host
  nginx:
    restart: always
    build:
      context: ./nginx
      network: host
    ports:
      - 80:80
