version: '3'
services:
  nextjs:
    build: ./
    # networks:
    # - nextts-rest-redux-panel-nginx_host
  nginx:
    build: ./nginx
    # networks:
    # - nextts-rest-redux-panel-nginx_host
    ports:
      - 80:80
# networks:
#   host:
#     driver: host
networks:
  default:
    external:
      name: nextts-rest-redux-panel-nginx_host
